version: '3'
services:
  game:
    image: game:latest
    container_name: Application_using_pygame
    build:
      context: .
      dockerfile: Dockerfile-game
    privileged: true
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    user: "1000:1000"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/dbus:/run/dbus
      - /dev/shm:/dev/shm
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /var/run/dbus:/var/run/dbus
      - /home/minhngoc/Downloads:/home/docker
    environment:
      - DISPLAY
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - XDG_RUNTIME_DIR=/run/user/1000
      
  build-sql:
    image: build-sql:latest
    container_name: Application_using_mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3306:3306"

